### ISSUE TITLE
make install prompts the user with error (due to missing doc files)

### ISSUE THREAD

**Issue by chris9182** [aglanger/CDPKit#1]
installing this toolkit with the following:

```
mkdir build
cd build
cmake ..
make
make install
```
yields an error at the end of make install indicating that the */build/Doc/C++-API/html and */build/Doc/Python-API/html folders are missing. 

I would suggest either not requiring those folders or running `doxygen` in */build/Doc/C++-API/ and */build/Doc/Python-API/ beforehand if available.

**Comment by seidelt** [comment]
The reported issue has been fixed and an error due to missing API-doc files should no longer occur
